[General]
FETCH_INTERVAL  = 4
MIL_PREFIX_LIST = 7CF
TAR1090_URL     = http://127.0.0.1:8080/data/aircraft.json
BLINK_MILITARY  = true
VERBOSE         = false

[Audio]
#
# Note, the last 'ATC_STREAM_URL' is the effective URL
#
ATC_STREAM_URL = https://d.liveatc.net/zkc_mci          # ZKC Kansas City Center
ATC_STREAM_URL = https://d.liveatc.net/kjfk_arinc       # ARINC (JFK/LGA Area), New York
ATC_STREAM_URL = https://d.liveatc.net/kjfk_del3        # KJFK Clearance Delivery #1, New York
ATC_STREAM_URL = https://d.liveatc.net/kjfk_atis        # KJFK D-ATIS (Weather info), New York
ATC_STREAM_URL = https://d.liveatc.net/eham_app_119055  # Schiphol Approach/Departure (119.055 MHz). Rather active
ATC_STREAM_URL = https://s1-fmt2.liveatc.net/vhhh5      # Hong Kong ATC. Very active.

ATC_VOLUME = 70
AUTO_START = true

[Location]
LAT       = 60.3045800
LON       = 5.3046400
AREA_NAME = Bergen
RADIUS_NM = 200

[Display]
SCREEN_WIDTH     = 960
SCREEN_HEIGHT    = 640
FPS              = 6
MAX_TABLE_ROWS   = 10
FONT_PATH        = $0/TerminusTTF-4.49.3.ttf
BACKGROUND_PATH  =
HEADER_FONT_SIZE = 32
RADAR_FONT_SIZE  = 22
TABLE_FONT_SIZE  = 22
BOTTOM_FONT_SIZE = 22
